server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
        
        - id: LIBRARYMANAGEMENT-SERVICE 
          uri: lb://LIBRARYMANAGEMENT-SERVICE 
          predicates:
            - Path=/api/book/**
            
        - id: REPORT-SERVICE 
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/report/**
            
        - id: USERMANAGEMENT-SERVICE 
          uri: lb://USERMANAGEMENT-SERVICE 
          predicates:
            - Path=/api/**
            
        
            
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost      
     
  main:
    web-application-type: reactive
